# Generated by Django 5.0.4 on 2024-05-02 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_rename_postal_code_address_pincode'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='customer_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.customeruser'),
        ),
    ]
