# Generated by Django 5.0.4 on 2024-06-14 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restrouser',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='restrouser',
            name='stars',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
