# Generated by Django 5.0.4 on 2024-06-12 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restrouser',
            name='menu_id',
        ),
        migrations.RemoveField(
            model_name='restromenuimage',
            name='restro_user_id',
        ),
        migrations.RemoveField(
            model_name='restrouser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='restrouser',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='RestroMenu',
        ),
        migrations.DeleteModel(
            name='RestroMenuImage',
        ),
        migrations.DeleteModel(
            name='RestroUser',
        ),
    ]
